More specific gl version error message
ValueError: Requested OpenGL version 450, got version 410

vs.

ValueError: The version required is not provided